services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    network_mode: host
    volumes:
      - ..:/workspace:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CAMERA_1_URL=http://host.docker.internal:9000/stream
    command: sleep infinity
